<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <DefineConstants>HTTPCLIENT</DefineConstants>
        <TargetFrameworks>net5.0;net6.0;net7.0;net8.0</TargetFrameworks>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.1.0"/>
        <PackageReference Include="NUnit" Version="3.13.3"/>
        <PackageReference Include="NUnit3TestAdapter" Version="4.2.1"/>
        <PackageReference Include="NUnit.Analyzers" Version="3.3.0"/>
        <PackageReference Include="coverlet.collector" Version="3.1.2"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\TOSNetCoreNew\TOSNetCoreNew.csproj" />
        <Compile Include="..\TestTOS\ClearEnv.cs">
            <Link>ClearEnv.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\Env.cs">
            <Link>Env.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\TestAppendObject.cs">
          <Link>TestAppendObject.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\TestBucket.cs">
          <Link>TestBucket.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\TestCopyObject.cs">
          <Link>TestCopyObject.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\TestGetObject.cs">
          <Link>TestGetObject.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\TestGetObjectToFile.cs">
          <Link>TestGetObjectToFile.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\TestListObjects.cs">
          <Link>TestListObjects.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\TestMultipartList.cs">
          <Link>TestMultipartList.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\TestMultipartUpload.cs">
          <Link>TestMultipartUpload.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\TestObjectTagging.cs">
          <Link>TestObjectTagging.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\TestPreSignedURL.cs">
          <Link>TestPreSignedURL.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\TestPutObject.cs">
          <Link>TestPutObject.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\TestPutObjectAcl.cs">
          <Link>TestPutObjectAcl.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\TestPutObjectFromFile.cs">
          <Link>TestPutObjectFromFile.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\TestRestoreObject.cs">
          <Link>TestRestoreObject.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\TestSetObjectMeta.cs">
          <Link>TestSetObjectMeta.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\TestUploadFile.cs">
          <Link>TestUploadFile.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\Util.cs">
            <Link>Util.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\LifecycleTestSupport.cs">
            <Link>LifecycleTestSupport.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\TestBucketAccessMonitor.cs">
            <Link>TestBucketAccessMonitor.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\TestBucketLifecycle.cs">
            <Link>TestBucketLifecycle.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\TestBucketVersioning.cs">
            <Link>TestBucketVersioning.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\TestCopyResponseParse.cs">
            <Link>TestCopyResponseParse.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\TestLifecycleResponseErrors.cs">
            <Link>TestLifecycleResponseErrors.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\TestObjectExpires.cs">
            <Link>TestObjectExpires.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\TestObjectLifecycleMetadata.cs">
            <Link>TestObjectLifecycleMetadata.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\TestObjectSetLifecycle.cs">
            <Link>TestObjectSetLifecycle.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\TestObjectSetLifecycleByTag.cs">
            <Link>TestObjectSetLifecycleByTag.cs</Link>
        </Compile>
        <Compile Include="..\TestTOS\TestObjectSetManagement.cs">
            <Link>TestObjectSetManagement.cs</Link>
        </Compile>
    </ItemGroup>


</Project>
